name: quade
description: A new Flutter project.
publish_to: 'none'
version: 1.0.9
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  dart_appwrite: ^19.4.0
  provider: ^6.1.5+1
  markdown_widget: ^2.3.2
  styled_text: ^8.1.0
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
